# renovate: datasource=docker depName=mcr.microsoft.com/devcontainers/javascript-node
FROM mcr.microsoft.com/devcontainers/javascript-node:22.20.0-bookworm@sha256:8ecd955dc231543929c46db04ab1a8962642bed804a84cdebb87a971dd5916d8
